### ISSUE TITLE
Issue when table is added on existing document with other table. 

### ISSUE THREAD

**Issue by alixv1** [UNIT6-open/TemplateEngine.Docx#22]
Hello,

I have a word document that contains multiple tables generated by the engine. When i insert a new table between 2 existing table ( more precisely, i add a new paragraph, in this new paragraph i add a new table generated by the engine) when i generate the new word document, all tables the first row. I add a simple example to reproduce the issue. The sample define 2 templates : Test1 contains only 2 table. Test2 contains a third table between the two table. You'll notice that the generated word based on Test2 template contains duplicate rows.   
[TemplateDocx.zip](https://github.com/UNIT6-open/TemplateEngine.Docx/files/754330/TemplateDocx.zip)

**Comment by lancheg** [comment]
Hello!

Output file based on Test2.docx template contains duplicate rows too.
It is because of the placeholders. You need to replace the text 'Click here to enter text.' in your templates with some another text and it will work.
Your example with fixed templates: 
[TemplateDocx.zip](https://github.com/UNIT6-open/TemplateEngine.Docx/files/757771/TemplateDocx.zip)

**Comment by alixv1** [comment]
Indeed, with text Inside cells it's ok. Thanks.
